version: "3"

services:
  nginx:
    image: nginx:alpine
    container_name: sites-nginx
    working_dir: /app
    volumes:
      - ../sites:/app
      - ./nginx/cert:/etc/cert
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
      - "443:443"
    networks:
      sites-net:
        ipv4_address: 10.5.0.5
    privileged: true

  php-fpm:
    container_name: sites-php
    build: ./php-fpm
    working_dir: /app
    volumes:
      - ../sites:/app
      - ./php-fpm/php-ini-overrides.ini:/usr/local/etc/php/conf.d/99-overrides.ini
      - ./php-fpm/fpm-overrides.conf:/usr/local/etc/php-fpm.d/z-overrides.conf
    networks:
      sites-net:
        ipv4_address: 10.5.0.6
    privileged: true
    environment:
      XDEBUG_CONFIG: "remote_host=host.docker.internal remote_port=9001 remote_enable=1 remote_autostart=1"

  mongodb:
    container_name: sites-mongo
    build: ./mongodb/
    command: ["--bind_ip_all"]
    ports:
      - "21038:21038"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: tko7510
      MONGO_INITDB_DATABASE: devdb
    networks:
      sites-net:
        ipv4_address: 10.5.0.7
    expose: 
      - 21038
    volumes:
      - ./mongodb/data:/data/db

networks:
  sites-net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
